#!/bin/bash
if  xdotool getwindowfocus getwindowname | grep -E ".*Firefox$"
then
	xdotool key Ctrl+Tab
elif xdotool getwindowfocus getwindowname | grep -E "Alacritty"
then
	xdotool key Shift+Right
fi

