#!/bin/bash 
killall gnome-screenshot
gnome-screenshot -i -a & fusuma-sendkey ENTER
wait
cd ~/Pictures
a=$(ls -Art | tail -n 1)
if [[ $XDG_SESSION_TYPE == "x11" ]];
then
     xclip -selection clipboard -t image/png -i "$a"
else
     wl-copy < "$a"
fi
